# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=models.TextField(),
        ),
        migrations.RemoveField(
            model_name='posts',
            name='tag',
        ),
        migrations.AddField(
            model_name='posts',
            name='tag',
            field=models.ManyToManyField(to='posts.Tags', verbose_name=b'\xe6\xa0\x87\xe7\xad\xbe'),
        ),
    ]
